### ISSUE TITLE
Cannot send pictures from the Photo-App on iPhone with german system language

### ISSUE THREAD

**Issue by Soljanka** [noenic/ShareFall#1]
iPhone 8 with iOS 15.5

Sending files via the files app does work; however not via the Photos App. I always get the error, that I do not have the required rights to do so as seen in the attached screenshot
![Bild](https://user-images.githubusercontent.com/7444116/178149947-493b431b-bdc6-48ed-a21f-9ba1b60adf4a.png)

If i tap on the error-message it jumps to the following block inside the shortcut
<img width="375" alt="Bild" src="https://user-images.githubusercontent.com/7444116/178149681-f7110a74-dbd1-4357-b8c9-f6690c463062.png">

**Comment by noenic** [comment]
it's because for some strange reason Apple doesn't allow to take content directly from the photo application. I found a workaround to this, you can see it above, just convert the image or video.

The problem here I guess is that to differentiate the type of content you want to send you have to make textual comparison with the type in input. Since your device is in German there is a good chance that you will have to change the name of the type in the condition.
![IMG_6797](https://user-images.githubusercontent.com/75330764/178150080-c2946731-13da-4a11-980e-e2d2e9728901.jpeg)

In french it is "Multimé(dia photo)"  but since in german photo is spelled "Foto".

that's why at each shortcut startup it displays the file type in the language of the device. 
I think that replacing "dia photo" by a part of the type name in your language the condition should work

I also noticed a bug when trying to copy text. I fixed the problem and I will commit it in a few minutes, it will have to replace the python file and the shortcut

**Comment by noenic** [comment]
I will try to add a translation action in a future version but for the moment I don't know if it is really reliable.

**Comment by Soljanka** [comment]
You are right, I changed the language of my phone to french and it does work now - thus just changing the condition should work for me. But how do you see the type of a file in iOS? Neither the files nor the photos app provides these information.

**Comment by noenic** [comment]
When the script runs first you should get an alert notification with the name of the file type in the language of the device.
(URL,Text,Image). 
![IMG_6798](https://user-images.githubusercontent.com/75330764/178152816-4d1bf421-4b23-4f35-b435-867166c95fc2.png)

**Comment by Soljanka** [comment]
Ahh it's that simple :)
FYI it's "Fotomedien" in german and after changing the condition I can now transfer pictures via Photo-App aswell.

**Comment by Soljanka** [comment]
I did skim the rest and changed other instances where it might go wrong on a german iPhone. I'll test it a couple of days and upload the shortcut then.

**Comment by noenic** [comment]
Awesome, did you make the changes on the last version of the shortcut?
There was a bug with the text copy, only a part of the text was transmitted.
It was necessary to modify the __init__.py as well as the shortcut itself.

**Comment by Soljanka** [comment]
Unfortuantely not; but I just downloaded the latest version (1.5) and will change it again; will be no hassle since I know what to edit now.

But I struggle at the initial setup now - where exactly do I need to put the SSID of the network? There are two comments directly among each other - it looks like there is a field missing

**Comment by noenic** [comment]
It's really easy, just put the name of your SSID in the key section, and the IP in the value section.
![IMG_6799](https://user-images.githubusercontent.com/75330764/178156325-6c0aa6dc-3cef-4afc-88bd-da68f2907541.jpeg)

here is mine for exemple

one key is empty, it's considered as the default when the "Get wifi name" action returns nothing. Here goes the IP of your computer when it's connected through Hotspot.

now every time you start the script it will take the IP adresse of your computer on the defined network. I needed this because I travel a lot between my student appartement and my home and my hotspot when at the university

**Comment by Soljanka** [comment]
hmm that's exactly how I did it. I think there is a simple mistake in the current ShareFallServer.bat. 
`py .\__main__.py" 80 -d .\share -t "token"`
Using this bat-file will not start the server - I just see the command prompt for a second and that's it

I am using the "old" ShareFallServer.bat and it's working. But I am curious: What is the advantage of the IP over the computer's name? I usually use the computer's name anyway since I usually get a different IP adress every time I start my notebook.

**Comment by noenic** [comment]
Oh I can see the problem, there is a **"**  that shouldn't be here.
Gonna fix that.
Since the starting problem is solved can we mark this thread as closed? unless there are other problems?

**Comment by Soljanka** [comment]
Yes, it's awesome, thanks a lot for the effort

The following shortcut does the trick for now on my german iPhone: https://www.icloud.com/shortcuts/32b8421080d6413bb2353cb14934215b
